version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - sinatra

  sinatra:
    #image: my-ruby:dockerfile
    build: ./sinatra
    command: ruby app.rb -o 0.0.0.0
    ports:
      - 4567:4567
    volumes:
      - ./sinatra:/opt/myapp
    working_dir: /opt/myapp
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf.d/charset.cnf:/etc/mysql/conf.d/charset.cnf
